// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OakdaleRolbal.Persistence;

#nullable disable

namespace OakdaleRolbal.Persistence.Migrations
{
    [DbContext(typeof(OakdaleRolbalDbContext))]
    partial class OakdaleRolbalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.ClubMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BlockedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("InvitedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimaryClub")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("JoinedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MembershipNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "UserId")
                        .IsUnique();

                    b.ToTable("ClubMemberships");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BowlsPerPlayer")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ChampionOfChampionsTarget")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("DefaultEnds")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultStageType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("DefaultTargetScore")
                        .HasColumnType("integer");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("FinalEnds")
                        .HasColumnType("integer");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("KeepJackInPlaceAfterContact")
                        .HasColumnType("boolean");

                    b.Property<bool>("KeepJackInPlaceAfterDelivery")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaximumMembershipYears")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumAgeYears")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumEntriesForRoundRobin")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("ReplayBurntEnds")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresClubColoursForFinal")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresMarker")
                        .HasColumnType("boolean");

                    b.Property<string>("ScoringType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("TeamSize")
                        .HasColumnType("integer");

                    b.Property<bool>("UseHandicap")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseJackSpotMarking")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CompetitionDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b6d4cac-c917-4f3f-968b-b2ffc3c6bb9f"),
                            BowlsPerPlayer = 4,
                            Category = "Open",
                            ChampionOfChampionsTarget = "WPBA Champion of Champions - Ladies Open",
                            Code = "L0101",
                            DefaultStageType = "Knockout",
                            DefaultTargetScore = 21,
                            EntryType = "Individual",
                            Format = "Singles",
                            Gender = "Ladies",
                            KeepJackInPlaceAfterContact = false,
                            KeepJackInPlaceAfterDelivery = false,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Ladies Open Singles",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = true,
                            ScoringType = "FirstToTargetShots",
                            TeamSize = 1,
                            UseHandicap = false,
                            UseJackSpotMarking = false
                        },
                        new
                        {
                            Id = new Guid("26024be8-78bf-4117-a77f-f5c700d2eeb6"),
                            BowlsPerPlayer = 4,
                            Category = "Senior",
                            ChampionOfChampionsTarget = "WPBA Champion of Champions - Ladies Senior",
                            Code = "L0102",
                            DefaultStageType = "Knockout",
                            DefaultTargetScore = 21,
                            EntryType = "Individual",
                            Format = "Singles",
                            Gender = "Ladies",
                            KeepJackInPlaceAfterContact = false,
                            KeepJackInPlaceAfterDelivery = false,
                            MinimumAgeYears = 60,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Ladies Senior Singles",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = true,
                            ScoringType = "FirstToTargetShots",
                            TeamSize = 1,
                            UseHandicap = false,
                            UseJackSpotMarking = false
                        },
                        new
                        {
                            Id = new Guid("f2b29233-a719-48eb-bad0-22dfd6cded4d"),
                            BowlsPerPlayer = 4,
                            Category = "Novice",
                            ChampionOfChampionsTarget = "WPBA Champion of Champions - Ladies Novice",
                            Code = "L0103",
                            DefaultStageType = "Knockout",
                            DefaultTargetScore = 21,
                            EntryType = "Individual",
                            Format = "Singles",
                            Gender = "Ladies",
                            KeepJackInPlaceAfterContact = false,
                            KeepJackInPlaceAfterDelivery = false,
                            MaximumMembershipYears = 3,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Ladies Novice Singles",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = true,
                            ScoringType = "FirstToTargetShots",
                            TeamSize = 1,
                            UseHandicap = false,
                            UseJackSpotMarking = false
                        },
                        new
                        {
                            Id = new Guid("c6fc77b3-2771-4f53-b650-c1d8bdb5d9d9"),
                            BowlsPerPlayer = 4,
                            Category = "Handicap",
                            Code = "L0104",
                            DefaultStageType = "Knockout",
                            DefaultTargetScore = 21,
                            EntryType = "Individual",
                            Format = "Singles",
                            Gender = "Ladies",
                            KeepJackInPlaceAfterContact = false,
                            KeepJackInPlaceAfterDelivery = false,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Ladies Handicap Singles",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = true,
                            ScoringType = "FirstToTargetShots",
                            TeamSize = 1,
                            UseHandicap = true,
                            UseJackSpotMarking = false
                        },
                        new
                        {
                            Id = new Guid("de5a1796-4cb7-4172-9a9d-867c614198b2"),
                            BowlsPerPlayer = 4,
                            Category = "Consistency",
                            Code = "L0105",
                            DefaultStageType = "Knockout",
                            DefaultTargetScore = 100,
                            EntryType = "Individual",
                            Format = "Singles",
                            Gender = "Ladies",
                            KeepJackInPlaceAfterContact = false,
                            KeepJackInPlaceAfterDelivery = false,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Ladies Consistency Singles",
                            Notes = "Best four live bowls on each end score points toward a 100-point target.",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = true,
                            ScoringType = "FirstToTargetPoints",
                            TeamSize = 1,
                            UseHandicap = false,
                            UseJackSpotMarking = true
                        },
                        new
                        {
                            Id = new Guid("10ff6ee2-969d-43a2-b982-7dc7090d3fb8"),
                            BowlsPerPlayer = 2,
                            Category = "TwoBowls",
                            Code = "L0106",
                            DefaultStageType = "Knockout",
                            DefaultTargetScore = 21,
                            EntryType = "Individual",
                            Format = "Singles",
                            Gender = "Ladies",
                            KeepJackInPlaceAfterContact = true,
                            KeepJackInPlaceAfterDelivery = true,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Ladies 2 Bowls Singles",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = false,
                            ScoringType = "FirstToTargetShots",
                            TeamSize = 1,
                            UseHandicap = false,
                            UseJackSpotMarking = false
                        },
                        new
                        {
                            Id = new Guid("834ba881-a6d4-4691-a8aa-58f779d2acfb"),
                            BowlsPerPlayer = 4,
                            Category = "Nominated",
                            Code = "L0207",
                            DefaultEnds = 15,
                            DefaultStageType = "Knockout",
                            EntryType = "Team",
                            FinalEnds = 18,
                            Format = "Pairs",
                            Gender = "Ladies",
                            KeepJackInPlaceAfterContact = false,
                            KeepJackInPlaceAfterDelivery = false,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Ladies Nominated Pairs",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = false,
                            ScoringType = "HighestShotsAfterFixedEnds",
                            TeamSize = 2,
                            UseHandicap = false,
                            UseJackSpotMarking = false
                        },
                        new
                        {
                            Id = new Guid("eb91b2c3-5c8d-4118-8746-cae922af3a8d"),
                            BowlsPerPlayer = 4,
                            Category = "Open",
                            ChampionOfChampionsTarget = "WPBA Champion of Champions - Mens Open",
                            Code = "M0101",
                            DefaultStageType = "Knockout",
                            DefaultTargetScore = 21,
                            EntryType = "Individual",
                            Format = "Singles",
                            Gender = "Mens",
                            KeepJackInPlaceAfterContact = false,
                            KeepJackInPlaceAfterDelivery = false,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Mens Open Singles",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = true,
                            ScoringType = "FirstToTargetShots",
                            TeamSize = 1,
                            UseHandicap = false,
                            UseJackSpotMarking = false
                        },
                        new
                        {
                            Id = new Guid("e990da92-ccaf-49fa-8d74-a6480c9109d6"),
                            BowlsPerPlayer = 4,
                            Category = "Senior",
                            ChampionOfChampionsTarget = "WPBA Champion of Champions - Mens Senior",
                            Code = "M0102",
                            DefaultStageType = "Knockout",
                            DefaultTargetScore = 21,
                            EntryType = "Individual",
                            Format = "Singles",
                            Gender = "Mens",
                            KeepJackInPlaceAfterContact = false,
                            KeepJackInPlaceAfterDelivery = false,
                            MinimumAgeYears = 60,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Mens Senior Singles",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = true,
                            ScoringType = "FirstToTargetShots",
                            TeamSize = 1,
                            UseHandicap = false,
                            UseJackSpotMarking = false
                        },
                        new
                        {
                            Id = new Guid("fef517b6-84f6-412f-8c6b-cabf5d399414"),
                            BowlsPerPlayer = 4,
                            Category = "Novice",
                            ChampionOfChampionsTarget = "WPBA Champion of Champions - Mens Novice",
                            Code = "M0103",
                            DefaultStageType = "Knockout",
                            DefaultTargetScore = 21,
                            EntryType = "Individual",
                            Format = "Singles",
                            Gender = "Mens",
                            KeepJackInPlaceAfterContact = false,
                            KeepJackInPlaceAfterDelivery = false,
                            MaximumMembershipYears = 3,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Mens Novice Singles",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = true,
                            ScoringType = "FirstToTargetShots",
                            TeamSize = 1,
                            UseHandicap = false,
                            UseJackSpotMarking = false
                        },
                        new
                        {
                            Id = new Guid("e18fd27c-6dcf-4f42-9f18-9f61cfb786d7"),
                            BowlsPerPlayer = 4,
                            Category = "Handicap",
                            Code = "M0104",
                            DefaultStageType = "Knockout",
                            DefaultTargetScore = 21,
                            EntryType = "Individual",
                            Format = "Singles",
                            Gender = "Mens",
                            KeepJackInPlaceAfterContact = false,
                            KeepJackInPlaceAfterDelivery = false,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Mens Handicap Singles",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = true,
                            ScoringType = "FirstToTargetShots",
                            TeamSize = 1,
                            UseHandicap = true,
                            UseJackSpotMarking = false
                        },
                        new
                        {
                            Id = new Guid("8db55e84-8668-448c-b2e1-31936abf4b75"),
                            BowlsPerPlayer = 4,
                            Category = "Consistency",
                            Code = "M0105",
                            DefaultStageType = "Knockout",
                            DefaultTargetScore = 100,
                            EntryType = "Individual",
                            Format = "Singles",
                            Gender = "Mens",
                            KeepJackInPlaceAfterContact = false,
                            KeepJackInPlaceAfterDelivery = false,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Mens Consistency Singles",
                            Notes = "Best four live bowls on each end score points toward a 100-point target.",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = true,
                            ScoringType = "FirstToTargetPoints",
                            TeamSize = 1,
                            UseHandicap = false,
                            UseJackSpotMarking = true
                        },
                        new
                        {
                            Id = new Guid("e9fdcb7d-b98f-4927-ac43-8a36d3222d29"),
                            BowlsPerPlayer = 2,
                            Category = "TwoBowls",
                            Code = "M0106",
                            DefaultStageType = "Knockout",
                            DefaultTargetScore = 21,
                            EntryType = "Individual",
                            Format = "Singles",
                            Gender = "Mens",
                            KeepJackInPlaceAfterContact = true,
                            KeepJackInPlaceAfterDelivery = true,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Mens 2 Bowls Singles",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = false,
                            ScoringType = "FirstToTargetShots",
                            TeamSize = 1,
                            UseHandicap = false,
                            UseJackSpotMarking = false
                        },
                        new
                        {
                            Id = new Guid("3989d7c6-eab6-4369-b85c-44de34ac72c9"),
                            BowlsPerPlayer = 4,
                            Category = "Nominated",
                            Code = "M0207",
                            DefaultEnds = 15,
                            DefaultStageType = "Knockout",
                            EntryType = "Team",
                            FinalEnds = 18,
                            Format = "Pairs",
                            Gender = "Mens",
                            KeepJackInPlaceAfterContact = false,
                            KeepJackInPlaceAfterDelivery = false,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Mens Nominated Pairs",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = false,
                            ScoringType = "HighestShotsAfterFixedEnds",
                            TeamSize = 2,
                            UseHandicap = false,
                            UseJackSpotMarking = false
                        },
                        new
                        {
                            Id = new Guid("1fe2ff17-1275-467f-b4de-d5fe4287b2cb"),
                            BowlsPerPlayer = 4,
                            Category = "Nominated",
                            Code = "X0201",
                            DefaultEnds = 15,
                            DefaultStageType = "Knockout",
                            EntryType = "Team",
                            FinalEnds = 18,
                            Format = "Pairs",
                            Gender = "Mixed",
                            KeepJackInPlaceAfterContact = false,
                            KeepJackInPlaceAfterDelivery = false,
                            MinimumEntriesForRoundRobin = 8,
                            Name = "Mixed Nominated Pairs",
                            ReplayBurntEnds = true,
                            RequiresClubColoursForFinal = true,
                            RequiresMarker = false,
                            ScoringType = "HighestShotsAfterFixedEnds",
                            TeamSize = 2,
                            UseHandicap = false,
                            UseJackSpotMarking = false
                        });
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClubMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("RejectedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ClubMembershipId");

                    b.HasIndex("CompetitionTeamId")
                        .IsUnique();

                    b.HasIndex("CompetitionEventId", "ClubMembershipId")
                        .IsUnique();

                    b.HasIndex("CompetitionEventId", "CompetitionTeamId")
                        .IsUnique();

                    b.ToTable("CompetitionEntries");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DrawDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EntryCloseOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EntryFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("EntryOpenOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionDefinitionId");

                    b.HasIndex("ClubId", "CompetitionDefinitionId", "Season")
                        .IsUnique();

                    b.ToTable("CompetitionEvents");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndsScheduled")
                        .HasColumnType("integer");

                    b.Property<int?>("ExtraEndsPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Rink")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StageType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionEventId");

                    b.ToTable("CompetitionMatches");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionMatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClubMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionMatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FinalPoints")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("FinalScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<decimal>("StartingScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionTeamId");

                    b.HasIndex("CompetitionMatchId", "Slot")
                        .IsUnique();

                    b.ToTable("CompetitionMatchParticipants");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionMatchScorecard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionMatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("SegmentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("WinningValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionMatchId")
                        .IsUnique();

                    b.ToTable("CompetitionMatchScorecards");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionMatchSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionMatchScorecardId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReplay")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("PointsForParticipantOne")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PointsForParticipantTwo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ScoreForParticipantOne")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ScoreForParticipantTwo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionMatchScorecardId", "Sequence")
                        .IsUnique();

                    b.ToTable("CompetitionMatchSegments");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Seed")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SkipMembershipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionEventId");

                    b.ToTable("CompetitionTeams");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionTeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSkip")
                        .HasColumnType("boolean");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClubMembershipId");

                    b.HasIndex("CompetitionTeamId", "ClubMembershipId")
                        .IsUnique();

                    b.ToTable("CompetitionTeamMembers");
                });

            modelBuilder.Entity("OakdaleRolbal.Persistence.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2683966-f6bd-4aa4-bbe2-b27aa3709189"),
                            ConcurrencyStamp = "3e00ce65-2e77-4322-938b-d4d7b374e35a",
                            Description = "Platform administrators with internal operational access.",
                            IsSystemRole = true,
                            Name = "InternalAdmin",
                            NormalizedName = "INTERNALADMIN"
                        },
                        new
                        {
                            Id = new Guid("93928d58-4764-4ba3-86bc-12ba6c7a0fe1"),
                            ConcurrencyStamp = "d6b85462-8946-4d4f-a849-273d81560ac0",
                            Description = "Club administrators who manage members, competitions, and club setup.",
                            IsSystemRole = true,
                            Name = "ClubAdmin",
                            NormalizedName = "CLUBADMIN"
                        },
                        new
                        {
                            Id = new Guid("2c6e6708-54f6-4f16-bfbf-b7bd0274c83c"),
                            ConcurrencyStamp = "38a459d9-d330-49e5-8f4f-f2897abddc53",
                            Description = "Standard club members who can enter competitions and manage their profile.",
                            IsSystemRole = true,
                            Name = "ClubMember",
                            NormalizedName = "CLUBMEMBER"
                        });
                });

            modelBuilder.Entity("OakdaleRolbal.Persistence.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("BsaRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RegisteredBowlerSinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("WpbaRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("OakdaleRolbal.Persistence.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("OakdaleRolbal.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("OakdaleRolbal.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("OakdaleRolbal.Persistence.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OakdaleRolbal.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("OakdaleRolbal.Persistence.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.ClubMembership", b =>
                {
                    b.HasOne("OakdaleRolbal.Domain.Entities.Club", "Club")
                        .WithMany("Memberships")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionEntry", b =>
                {
                    b.HasOne("OakdaleRolbal.Domain.Entities.ClubMembership", "ClubMembership")
                        .WithMany("CompetitionEntries")
                        .HasForeignKey("ClubMembershipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OakdaleRolbal.Domain.Entities.CompetitionEvent", "CompetitionEvent")
                        .WithMany("Entries")
                        .HasForeignKey("CompetitionEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OakdaleRolbal.Domain.Entities.CompetitionTeam", "CompetitionTeam")
                        .WithOne("Entry")
                        .HasForeignKey("OakdaleRolbal.Domain.Entities.CompetitionEntry", "CompetitionTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClubMembership");

                    b.Navigation("CompetitionEvent");

                    b.Navigation("CompetitionTeam");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionEvent", b =>
                {
                    b.HasOne("OakdaleRolbal.Domain.Entities.Club", "Club")
                        .WithMany("CompetitionEvents")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OakdaleRolbal.Domain.Entities.CompetitionDefinition", "CompetitionDefinition")
                        .WithMany("CompetitionEvents")
                        .HasForeignKey("CompetitionDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("CompetitionDefinition");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionMatch", b =>
                {
                    b.HasOne("OakdaleRolbal.Domain.Entities.CompetitionEvent", "CompetitionEvent")
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionEvent");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionMatchParticipant", b =>
                {
                    b.HasOne("OakdaleRolbal.Domain.Entities.CompetitionMatch", "CompetitionMatch")
                        .WithMany("Participants")
                        .HasForeignKey("CompetitionMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OakdaleRolbal.Domain.Entities.CompetitionTeam", "CompetitionTeam")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("CompetitionTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompetitionMatch");

                    b.Navigation("CompetitionTeam");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionMatchScorecard", b =>
                {
                    b.HasOne("OakdaleRolbal.Domain.Entities.CompetitionMatch", "CompetitionMatch")
                        .WithOne("Scorecard")
                        .HasForeignKey("OakdaleRolbal.Domain.Entities.CompetitionMatchScorecard", "CompetitionMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionMatch");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionMatchSegment", b =>
                {
                    b.HasOne("OakdaleRolbal.Domain.Entities.CompetitionMatchScorecard", "CompetitionMatchScorecard")
                        .WithMany("Segments")
                        .HasForeignKey("CompetitionMatchScorecardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionMatchScorecard");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionTeam", b =>
                {
                    b.HasOne("OakdaleRolbal.Domain.Entities.CompetitionEvent", "CompetitionEvent")
                        .WithMany("Teams")
                        .HasForeignKey("CompetitionEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionEvent");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionTeamMember", b =>
                {
                    b.HasOne("OakdaleRolbal.Domain.Entities.ClubMembership", "ClubMembership")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("ClubMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OakdaleRolbal.Domain.Entities.CompetitionTeam", "CompetitionTeam")
                        .WithMany("Members")
                        .HasForeignKey("CompetitionTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClubMembership");

                    b.Navigation("CompetitionTeam");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.Club", b =>
                {
                    b.Navigation("CompetitionEvents");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.ClubMembership", b =>
                {
                    b.Navigation("CompetitionEntries");

                    b.Navigation("TeamMemberships");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionDefinition", b =>
                {
                    b.Navigation("CompetitionEvents");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionEvent", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionMatch", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Scorecard");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionMatchScorecard", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("OakdaleRolbal.Domain.Entities.CompetitionTeam", b =>
                {
                    b.Navigation("Entry");

                    b.Navigation("MatchParticipants");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
